
const roleRoutes = {
    superAdmin: [
        "/home/dashboard",
        "/home/mapData",
        "/home/rideJourney",
        "/home/driverJourney",
        "/home/driverLogs",
        "/drivers/allDrivers",
        "/drivers/allOffers",
        "/drivers/liveDrivers",
        "/drivers/allDrivers",
        "/drivers/allVerified",
        "/rides/allRides",
        "/city",
        "/notification",
        "/issueAssigner",
        "/issueSolver",
        "/issueDetail",
        "/users",
        "/category",
        "/allUsersOffers",
        "/admin",
        "/pricing",
        '/blogs',
        '/blog/',
        '/tspMessages',
    ],
    admin: [
        "/home/dashboard",
        "/home/mapData",
        "/home/rideJourney",
        "/home/driverJourney",
        "/home/driverLogs",
        "/drivers/allDrivers",
        "/drivers/allOffers",
        "/drivers/liveDrivers",
        "/drivers/allDrivers",
        "/drivers/allVerified",
        "/rides/allRides",
        "/city",
        "/notification",
        "/issueAssigner",
        "/issueSolver",
        "/issueDetail",
        "/users",
        "/category",
        "/allUsersOffers",
    ],
    verifier: ["/home/dashboard", "/home/mapData", "/home/rideJourney", "/home/driverJourney", "/home/driverLogs", "/drivers/allDrivers", "/drivers/allOffers",
        "/drivers/liveDrivers",
        "/drivers/allDrivers",
        "/drivers/allVerified", "/allUsersOffers", "/notification",],
    userExplore: ["/home/dashboard", "/users"],
    verifierAndIssueAssigner: [
        "/home/dashboard",
        "/drivers/allDrivers",
        "/drivers/allOffers",
        "/drivers/liveDrivers",
        "/drivers/allDrivers",
        "/drivers/allVerified",
        "/issueAssigner",
        "/issueSolver",
        "/issueDetail",
        "/users"
    ],
    issueAssigner: ["/home/dashboard", "/issueAssigner", "/issueDetail", "/issueSolver"],
    issueSolver: ["/home/dashboard", "/issueSolver", "/issueDetail"],
    guest: ["/home/dashboard"],
    onlyNotifs: ['/home/dashboard', "/notification"],
};

export default roleRoutes;