name: Push-to-EC2
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        
      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
          
      - name: Execute remote commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            echo "Updating system..."
            sudo apt update
            sudo apt upgrade -y
            
            echo "Installing Apache..."
            sudo apt install -y apache2
            
            echo "Starting Apache..."
            sudo systemctl start apache2
            sudo systemctl enable apache2
            
            echo "Installing Node.js and npm..."
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt install -y nodejs
            
            echo "Building application..."
            cd ${{ secrets.TARGET_DIR }}
            npm install
            sudo npm run build
            
            echo "Deploying to /var/www/html..."
            cd build
            sudo cp -r * /var/www/html/
            
            echo "Restarting Apache..."
            sudo systemctl restart apache2
